fiber:
  chain: /dev.toml
  auto_announce_node: true
  announce_private_addr: true
  watchtower_check_interval_seconds: 1
  gossip_store_maintenance_interval_ms: 1000
  gossip_network_maintenance_interval_ms: 1000
  listening_addr: "/ip4/0.0.0.0/tcp/8228"
  announced_addrs:
    - "/dns4/fiber-node3/tcp/8228"
  announced_node_name: "fiber-node3"
  bootnode_addrs:
    - "/dns4/fiber-bootnode/tcp/8228/p2p/QmPi1oizWmjhFw6erAojoUFNpVyLs4XeVYAfzWHP1A7tTF"
  scripts:
    - name: FundingLock
      script:
        code_hash: 0x6c67887fe201ee0c7853f1682c0b77c0e6214044c156c7558269390a8afa6d7c
        hash_type: type
        args: 0x
      cell_deps:
        - cell_dep:
            out_point:
              tx_hash: 0x14f28bb0b08c6c24c73e206297a8dacb631c9bbbef1d654f105e3a61616ea36c # ckb_auth
              index: 0x5
            dep_type: code
    - name: CommitmentLock
      script:
        code_hash: 0x740dee83f87c6f309824d8fd3fbdd3c8380ee6fc9acc90b1a748438afcdf81d8
        hash_type: type
        args: 0x
      cell_deps:
        - cell_dep:
            out_point:
              tx_hash: 0x14f28bb0b08c6c24c73e206297a8dacb631c9bbbef1d654f105e3a61616ea36c #ckb_auth
              index: 0x6
            dep_type: code
rpc:
  listening_addr: 127.0.0.1:41716
  enabled_modules:
    - cch
    - channel
    - payment
    - graph
    - info
    - invoice
    - peer
    - watchtower
    - dev
    - prof
cch:
  ignore_startup_failure: true
  wrapped_btc_type_script_args: "0x32e555f3ff8e135cece1351a6a2971518392c1e30375c1e006ad0ce8eac07947"
  lnd_cert_path: ./deploy/lnd-init/lnd-ingrid/tls.cert

ckb:
  rpc_url: "http://ckb:8114"
  # udt whitelist, will be generated by udt-init
  tx_tracing_polling_interval_ms: 300
  udt_whitelist:
    - name: simple_udt
      script:
        code_hash: 0xe1e354d6d643ad42724d40967e334984534e0367405c5ae42a9d7d63d77df419
        hash_type: data
        args: 0x.*
      cell_deps:
      - cell_dep:
          out_point:
            tx_hash: 0x14f28bb0b08c6c24c73e206297a8dacb631c9bbbef1d654f105e3a61616ea36c
            index: 0x8
          dep_type: code

services:
  - fiber
  - rpc
  - ckb
